# 20170613
# Heatmap for topic models
# And dendrograms for topic models

# Heatmaps can be used for a single dataset or to compare two topic models.
# Dendrograms can only be used to group similar clusters of a single topic model.

# For the sendrograms it is needed that "dendrogram_plotter.R" is in the working directory to be sourced
# It is needed just to obtain the color visual. The grouping and black and white image are independent of that file


# Libraries
# These are libraries from my github account
# install.packages("devtools")
# library(devtools)
# install_github("cristianmejia00/Opener5")
# install_github("cristianmejia00/keywordGetter")
# install_github("cristianmejia00/heatmaps3")

library(Opener5)
library(keywordGetter)
library(heatmaps3)
library(SnowballC)

# Helper function
withStem <- function(list_of_keywords) {
  for (i in 1:length(list_of_keywords)) {
    stemWords <- sapply(list_of_keywords[[i]]$TERM, function(x) {
      wordStem(x, language = "en")
    })
    list_of_keywords[[i]]$TERM <- unname(stemWords)
  }
  return(list_of_keywords)
}


# Read the files.
# FOR TOPIC MODELS: It takes the "topic_words.csv" reports generated by topic_model_5.R
# One for each of the models to compare.
# Or repeate the same, for comparison within the same topic model
# FOR CLUSTERS: Put all mission.keyword.tsv files in a separated folder. Choose that folder when reading.

# Reading files
# IMPORTANT -- file paths MUST NOT contain other numbers other than the cluster in the "mission.keyword.#"
# i.e. intermediate folder names must not have numbers.
# x_axis <- fukan_Keywords_to_list(choose.dir())
# x_axis <- withStem(x_axis)

x_axis <- ALL_Topics # read_from_others_csv(file.choose()) %>% keywords_to_list
y_axis <- ALL_Topics # read_from_others_csv(file.choose()) %>% keywords_to_list

# Labeling (A short name for each topic model)
x_label <- "titech"
y_label <- "titech"

# Select the min and max similarity values to show (between 0 to 1; 1 highest similarity)
# If changed, always run "# Select the dots to show"
min_appear <- 0
max_appear <- 1

# Select dot size (pixels)
size <- 5

###########################################
# Reports
###########################################
# Heatmap scores as matrix
h_matrix <- heatmap_matrix(x_axis, y_axis, report = TRUE)

# Heatmap scores as list
h_edges <- heatmap_list(h_matrix, x_axis, y_axis, report = TRUE)

# Similarity boxplot
bpdata <- boxplot(h_edges$value)
bpdata$stats
bpdata$out

# Select the dots to show
appears <- sapply(round(h_edges$value, 3), function(x) {
  if (x >= min_appear & x <= max_appear) {
    1
  } else {
    0
  }
})

# Heatmap visualization
heatmap <- heatmap_viz(h_edges, x_label, y_label, appears = appears, size = size)
heatmap

##############################################
# Dendrogram
##############################################

# Compute distance matrix
# At this point we have different sources to compute the distance matrix
# From the cosine simialrity of probable terms, (Best results)
# From the cosine similarity of exclusive terms,
# From the t(Phi) table, the Topic by terms
# From the t(Theta) table, The Document by Topic (Worst results)

# The only condition is that it needs to be formated with the topics as rows.

# Plug the table
input_table <- h_matrix # t(theta) #h_matrix #t(phi)
row.names(input_table) <- c(1:K)
distance_matrix <- dist(input_table, method = "euclidean")

# Hierarchical clustering
clusterWC <- hclust(distance_matrix, method = "ward.D")

# Plot the dendrogram
par(cex = 0.5) # Change label size
plot(clusterWC, hang = -1)

# Assign points to clusters
ck <- 10
clusterGroups <- cutree(clusterWC, k = ck)
table(clusterGroups)
if (is.null(names(clusterGroups))) {
  names(clusterGroups) <- c(1:k)
}
names(clusterGroups)

# Find which cluster "Multidisciplinary Sciences" is in.
# clusterGroups["Multidisciplinary Sciences"]

# Create a list of clusters, with their contents
clusterContents <- lapply(c(1:ck), function(x) {
  names(clusterGroups[clusterGroups == x])
})

# Write in file for easy exploration
df <- data.frame(V1 = rep(NA, max(sapply(clusterContents, length)))) # Create a df of NA to handle the uneven length of clusters
for (i in 1:ck) {
  df[1:length(clusterContents[[i]]), i] <- clusterContents[[i]]
}
write.csv(df, file = "fromProbableWords_megaclusters-10.csv", na = "", row.names = FALSE)

# # load code of A2R function from online or locale
source("http://addictedtor.free.fr/packages/A2R/lastVersion/R/code.R")
# source("dendrogram_plotter.R")
# colored dendrogram
# op = par(bg = "#EFEFEF")
# op = par(cex = 0.4)
A2Rplot(clusterWC,
  k = ck, boxes = FALSE, col.up = "gray50",
  col.down = sample(rainbow(ck))
)

# par = op

# check: http://gastonsanchez.com/visually-enforced/how-to/2012/10/03/Dendrograms/
