

#==============================================================================
# Load settings
source("_3_entry_analysis.R")
if (settings$params$recursive_level == 0) {
  settings$params$recursive_level <- 1 # Must be 1 or higher for this to work. This change wont affect the other code.
}
###############################################################################
# Read input files
analysis_folder_path <- file.path(settings$metadata$bibliometrics_folder,
                                  settings$metadata$project_folder,
                                  settings$metadata$analysis_id)

network <- readr::read_csv(file.path(analysis_folder_path, "network_comp.csv"))
dataset_minimal <- readr::read_csv(file.path(analysis_folder_path, 
                                             settings$cno$clustering$algorithm,
                                             "dataset_clustered.csv"))

# Create network object
if (!settings$cno$using_mission_pairs_from_fukan) {
  print("Loading computed network")
  g1 <- graph_from_data_frame(network, directed = TRUE)
} else {
  # The network object is based on "mission.pairs.tsv" from Fukan's results
  print("Graph from mission pairs")
  g1 <- read.graph(network, format = "ncol")
}

# Verification
stopifnot(
  all(as.numeric(dataset_minimal$X_N) %in% as.numeric(V(g1)$name))
)

dataset_minimal <- dataset_minimal[match(V(g1)$name, dataset_minimal$X_N),]
stopifnot(
  all(as.numeric(dataset_minimal$X_N) == as.numeric(V(g1)$name))
)

###############################################################################
###############################################################################
###############################################################################
source("02_citation_network/03_recursive_clustering_WOS.R")

###############################################################################
###############################################################################
###############################################################################
# Save the file
# From the pov of this very code, this is actually the output folder. Where the files generated by this code will be placed.
results_folder_path <- file.path(settings$metadata$bibliometrics_folder,
                                 settings$metadata$project_folder,
                                 settings$metadata$analysis_id,
                                 settings$cno$clustering$algorithm,
                                 settings$cno$thresholding$threshold %>% as.character())
dir.create(results_folder_path, showWarnings = FALSE)

# Write the `dataset_minimal` which is created in 02_citation_network/02_louvain_Infomap.R
write.csv(dataset_minimal, 
          file = file.path(results_folder_path, "dataset_minimal.csv"), 
          row.names = FALSE)

# Write the edges counts
write.csv(edges_level1, 
          file = file.path(results_folder_path, "level0_edges_count.csv"), 
          row.names = TRUE)

if (settings$params$recursive_level >= 1) {
  write.csv(edges_level2, 
            file = file.path(results_folder_path, "level1_edges_count.csv"), 
            row.names = TRUE)
}

if (settings$params$recursive_level >= 2) {
  write.csv(edges_level3, 
            file = file.path(results_folder_path, "level2_edges_count.csv"), 
            row.names = TRUE)
}

if (settings$params$recursive_level >= 4) {
  write.csv(edges_level4, 
            file = file.path(results_folder_path, "level3_edges_count.csv"), 
            row.names = TRUE)
}

# The components settings and info
writeLines(RJSONIO::toJSON(settings$cno$thresholding, 
                           pretty = TRUE,
                           auto_unbox = TRUE),
           file.path(results_folder_path, "threshold_settings.json"))

# Print info to the console:
print(dataset_minimal$level0 %>% unique() %>% sort())
print(glue("Clusters: {dataset_minimal$level0 %>% unique() %>% length()}"))

print(dataset_minimal$subcluster_label1 %>% unique() %>% sort())
print(glue("Clusters: {dataset_minimal$subcluster_label1 %>% unique() %>% length()}"))

# Clean
rm(list = ls())
