services:
  pipeline:
    image: ghcr.io/cristianmejia00/clustering:latest
    working_dir: /workspace
    volumes:
      - ./docker:/workspace/docker
      - ./docker/credentials:/workspace/assets/credentials:ro
    stdin_open: true
    tty: true
