# ==============================================================================
# pipelines/analysis/citation_network/thresholding.R
#
# Applies recursive clustering and thresholding to the clustered dataset.
# ==============================================================================

source("utils/libraries.R")
source("utils/system_paths.R")
source("utils/load_config.R")

settings <- load_config("config_analysis.yml") |> add_legacy_aliases()
if (settings$params$recursive_level == 0) {
  settings$params$recursive_level <- 1 # Must be 1 or higher for this to work. This change wont affect the other code.
}
###############################################################################
# Read input files
analysis_folder_path <- file.path(
  settings$metadata$bibliometrics_folder,
  settings$metadata$project_folder,
  settings$metadata$analysis_id
)

network <- readr::read_csv(file.path(analysis_folder_path, "network_comp.csv"))
dataset_minimal <- readr::read_csv(file.path(
  analysis_folder_path,
  settings$cno$clustering$algorithm,
  "dataset_clustered.csv"
))

# Create network object
if (!settings$cno$using_mission_pairs_from_fukan) {
  print("Loading computed network")
  g1 <- graph_from_data_frame(network, directed = TRUE)
} else {
  # The network object is based on "mission.pairs.tsv" from Fukan's results
  print("Graph from mission pairs")
  g1 <- read.graph(network, format = "ncol")
}

# Verify and align IDs between clustered dataset and graph nodes.
# `network_comp.csv` is an edge list, so it may omit isolated vertices that are
# still present in `dataset_clustered.csv`.
dataset_ids <- suppressWarnings(as.numeric(dataset_minimal$X_N))
graph_ids <- suppressWarnings(as.numeric(V(g1)$name))

if (any(is.na(graph_ids))) {
  stop("Non-numeric vertex IDs found in network graph; cannot align to dataset_minimal$X_N.")
}

if (any(is.na(dataset_ids))) {
  invalid_rows <- sum(is.na(dataset_ids))
  warning(glue::glue(
    "Dropping {invalid_rows} row(s) from dataset_clustered.csv with missing or non-numeric X_N."
  ))
  dataset_minimal <- dataset_minimal[!is.na(dataset_ids), , drop = FALSE]
  dataset_ids <- dataset_ids[!is.na(dataset_ids)]
}

if (nrow(dataset_minimal) == 0) {
  stop("No valid rows remain in dataset_clustered.csv after filtering invalid X_N values.")
}

if (anyDuplicated(dataset_ids)) {
  stop("Duplicate X_N values found in dataset_clustered.csv; cannot map nodes uniquely.")
}

missing_in_dataset <- setdiff(unique(graph_ids), unique(dataset_ids))
if (length(missing_in_dataset) > 0) {
  preview <- paste(utils::head(missing_in_dataset, 10), collapse = ", ")
  stop(glue::glue(
    "{length(missing_in_dataset)} graph node ID(s) are missing in dataset_clustered.csv. First IDs: {preview}"
  ))
}

extra_in_dataset <- setdiff(unique(dataset_ids), unique(graph_ids))
if (length(extra_in_dataset) > 0) {
  dropped_rows <- sum(dataset_ids %in% extra_in_dataset)
  warning(glue::glue(
    "Dropping {dropped_rows} row(s) from dataset_clustered.csv that are not present in network_comp.csv."
  ))
}

dataset_minimal <- dataset_minimal[match(graph_ids, dataset_ids), , drop = FALSE]
dataset_minimal$X_N <- graph_ids

stopifnot(
  all(dataset_minimal$X_N == graph_ids)
)

###############################################################################
###############################################################################
###############################################################################
source(file.path(getwd(), "pipelines", "analysis", "citation_network", "helpers", "03_recursive_clustering_WOS.R"))

###############################################################################
###############################################################################
###############################################################################
# Save the file
# From the pov of this very code, this is actually the output folder. Where the files generated by this code will be placed.
results_folder_path <- file.path(
  settings$metadata$bibliometrics_folder,
  settings$metadata$project_folder,
  settings$metadata$analysis_id,
  settings$cno$clustering$algorithm,
  settings$cno$thresholding$threshold %>% as.character()
)
dir.create(results_folder_path, showWarnings = FALSE)

# Write the `dataset_minimal` which is created in pipelines/dataset/utils/02_citation_network/02_louvain_Infomap.R
write.csv(dataset_minimal,
  file = file.path(results_folder_path, "dataset_minimal.csv"),
  row.names = FALSE
)

# Write the edges counts
write.csv(edges_level1,
  file = file.path(results_folder_path, "level0_edges_count.csv"),
  row.names = TRUE
)

if (settings$params$recursive_level >= 1) {
  write.csv(edges_level2,
    file = file.path(results_folder_path, "level1_edges_count.csv"),
    row.names = TRUE
  )
}

if (settings$params$recursive_level >= 2) {
  write.csv(edges_level3,
    file = file.path(results_folder_path, "level2_edges_count.csv"),
    row.names = TRUE
  )
}

if (settings$params$recursive_level >= 4) {
  write.csv(edges_level4,
    file = file.path(results_folder_path, "level3_edges_count.csv"),
    row.names = TRUE
  )
}

# The components settings and info
writeLines(
  RJSONIO::toJSON(settings$cno$thresholding,
    pretty = TRUE,
    auto_unbox = TRUE
  ),
  file.path(results_folder_path, "threshold_settings.json")
)

# Print info to the console:
print(dataset_minimal$level0 %>% unique() %>% sort())
print(glue("Clusters: {dataset_minimal$level0 %>% unique() %>% length()}"))

print(dataset_minimal$subcluster_label1 %>% unique() %>% sort())
print(glue("Clusters: {dataset_minimal$subcluster_label1 %>% unique() %>% length()}"))
