# Topic-model-only runner
# Assumes dataset artifacts (including embeddings) already exist.

message("Topic-model embeddings are now generated by scripts/dataset_only.R")
message("Use the topic-model notebook(s) to run BERTopic clustering on precomputed embeddings.")
message("Expected artifacts under project/<filtered_folder>/<embed_profile>:")
message("- embeddings.npy")
message("- embeddings_ids.json")
message("- corpus.csv")
